### ISSUE TITLE
Missing dependecy

### ISSUE THREAD

**Issue by RileyTomasek** [auth0/webtask-tools#18]
It seems you are using `edges` [here](https://github.com/auth0/webtask-tools/blob/master/lib/index.js#L54), but it is not listed in your dependencies. Building a file with webpack catches this and requires the user to independently install edges in order to user this.

**Comment by NotMyself** [comment]
Hi @RileyTomasek,

At this time we are not going to be splitting this compiler into its own package and maintaining it. We also do not want to add the dependency to the package just to support this compiler. I am going to close this issue for now. We will revisit the topic when and if this compiler sees greater use in the community.

Thanks,

Bobby
