### ISSUE TITLE
Vulnerability in a pug dependency

### ISSUE THREAD

**Issue by antham** [auth0/webtask-tools#33]
The version of clean-css used by a pug dependency, is resolved to the version 3.4.28 but there is a vulnerability in versions below 4.1.11 (https://github.com/jakubpawlowicz/clean-css/commit/2929bafbf8cdf7dccb24e0949c70833764fa87e3).

**Comment by dukedave** [comment]
Per [this](https://github.com/pugjs/pug/pull/2989#issuecomment-374910604) we need to go from https://github.com/auth0/webtask-tools/blob/3da48e198bec7b0c017267932d59c20db7881252/package.json#L29 to `2.0.3`.

**Comment by antham** [comment]
I didn't see this part in the README => https://github.com/auth0/webtask-tools#issue-reporting , I don't know if what I reported fit this section but I would suggest to add an issue template for future case like this to warn anyone wanting to report a vulnerability

**Comment by dukedave** [comment]
@antham oh yeah, I didn't notice that either 😬 
Oh well. I _assume_ that this one is fine, since anyone doing an `npm audit` would see the vulnerability (i.e. this issue isn't really _disclosing_ anything).

---

FYI I also pinged Auth0 support and they said:

> Thank you for contacting Auth0 support. And thank you for submitting the PR. I am escalating this ticket to our engineering team to review and merge the changes. I will respond back to you as soon as I get a response back from them.

🤞
